### ISSUE TITLE
magic home firmware

### ISSUE THREAD

**Issue by mafyata** [jghaanstra/magic.home.wifi#6]
I am looking for original firmware for magic home controller . Mine is rgb with 24 ir remote controller zj wfmn-a v1.1. Last version was 33.v6

**Comment by jghaanstra** [comment]
This repo is from a app which is used to control Magic Home devices with the Homey domotica controller. It's not for discussing the firmware of Magic Home controllers.

**Comment by mafyata** [comment]
Yes, but someone may be got downloaded the firmware from the device.
