### ISSUE TITLE
Controllers are mixed-up in Homey

### ISSUE THREAD

**Issue by fvhuizen** [jghaanstra/magic.home.wifi#7]
Since last week i have issues with the Magic Home devices in Homey. I have two similar devices and they seems to get mixed up. When i try to manage one for example, the other device is changing instead of the device i choose. When i switch to the original Magic Home app on my phone everything works great.

I tried te reboot Homey, reboot the app, deleting the devices and adding them but without any improvement.

This is the diagnostic report ID, i hope you can guide me how to solve it.
7b98f980-dd26-40d0-b86e-de167429aef4

**Comment by jghaanstra** [comment]
Below are two parts of the diagnostics report.

> 2019-05-02 21:26:38 [log] [ManagerDrivers] [magichome] [0] { Error: connect EHOSTUNREACH 192.168.2.12:5577
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.2.12',
  port: 5577 }

> 2019-05-02 21:27:45 [err] [ManagerDrivers] [magichome] [2] { Error: connect ECONNREFUSED 192.168.2.14:5577
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.2.14',
  port: 5577 }

The only thing I see here is that the app is unable to connect to the controllers on 192.168.2.12 and 192.168.2.14. Are these the correct IP addresses and have you assigned static IP addresses for the controllers?

Although I put some mechanism in place which should detect if a controller gets a different IP address perhaps something went wrong here and the device was updated with the IP address of another device. It would be best to assign the address statically.

**Comment by jghaanstra** [comment]
Any news on this?

**Comment by fvhuizen** [comment]
I’m working on it. I replaced my router and access point because that wasn’t stable too. So I keep you informed

**Comment by jghaanstra** [comment]
I'm closing this due to lack of feedback, If you still experience issues let me know.
