### ISSUE TITLE
MagicHome lagging and errors at Athom Homey

### ISSUE THREAD

**Issue by kapusticka** [jghaanstra/magic.home.wifi#8]
Hi. I’ve just purchased MagicHome WiFi and IR module with LED strip. Everything looks good, but after a few minutes device MagicHome on Athom Homey lagging or can’t be use because of “Timed Out”  messages. I think it’s Athom Homey app issue because genuine iOS app “Magic Home” works great.

**Comment by kapusticka** [comment]
I think it’s Homey app wrong. Maybe issues with MagicHome servers. Because MagicHome work perfectly for me. But your  Athom Homey app lagging lot of times :(

**Comment by jghaanstra** [comment]
Could you explain why about 250 other users do not seem to have this problem?

What you could do is run the app from the command line using the Athom cli and the command `athom app run` and see if it gives me information on what is going on.

I'm closing this issue for not as I don't think it's a bug. Please continue this in the support forum so you can also get help from the community.
