### ISSUE TITLE
Homey krijgt geen contact met de led strip

### ISSUE THREAD

**Issue by Wibbel68** [jghaanstra/magic.home.wifi#9]
Ik hem geprobeerd via de app zelf en daar kan ik wel de led strip aan en uitzetten. 
App in homey twee keer gereset maar heeft niet geholpen. 
Succes met het oplossen.

**Comment by jghaanstra** [comment]
Please use the support forum for support questions. Github is for features and bugs.

**Comment by Wibbel68** [comment]
Sorry
